/*
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.basics.date

import java.util.Locale

import scala.collection.immutable.List
import scala.collection.immutable.Map

/**
 * The holiday calendars built into this library, as values, keyed by their identifiers.
 *
 * A holiday calendar is reference data: code that adjusts a date asks for a calendar by
 * identifier and is given one by the [[com.opengamma.strata.basics.ReferenceData]] it was
 * passed, so that an application whose own holidays are what matter can supply them. Most
 * applications, and every test and demonstration, want the calendars this library already
 * knows about instead, and this object is where those live. It is the single place the
 * built-in set is written down, and `ReferenceData.standard` is exactly this set presented as
 * reference data.
 *
 * Thirty calendars are published, in three groups and from three different kinds of source:
 *
 *   - twenty-five national and exchange calendars derived from rules, produced by
 *     [[GlobalHolidayCalendars]] - `GBLO` through `ZAJO` below;
 *   - one calendar whose dates are published rather than derived, the Thai bank calendar
 *     [[THBA]], built from the table in [[HolidayCalendarData]];
 *   - four calendars whose whole content follows from their names: [[NO_HOLIDAYS]],
 *     [[SAT_SUN]], [[FRI_SAT]] and [[THU_FRI]].
 *
 * ===The set and its names===
 *
 * The set is written down here as data, in the order the four name-derived calendars, then the
 * published calendar, then the twenty-five generated ones, and a name is resolved to the first
 * calendar of that order which claims it. Every calendar is reachable three ways that yield the
 * same value: by the constant naming it below, by its identifier through [[all]], and by name
 * through the two name views [[byName]] and [[byUpperName]]. Nothing here reads a file, a network
 * or any source outside this build, so the built-in set cannot differ between two runs or two
 * deployments of the same version.
 *
 * ===Initialisation order===
 *
 * Every member of this object is a `lazy val`, and that is load-bearing rather than merely an
 * optimisation. This object sits in a cycle the design intends: the JSON form of a calendar in
 * [[HolidayCalendar]] names the built-in calendars and so reads this object, the calendars are
 * generated by [[GlobalHolidayCalendars]], and those generators build their results with
 * `ImmutableHolidayCalendar.of` - back in [[HolidayCalendar]]. `ReferenceData.standard`, itself
 * computed on first use, reads [[deferredByIdentifier]]. A strict `val` anywhere in that cycle
 * would make the order in which these objects happen to be initialised load-bearing, and the
 * value observed by whichever member of the cycle ran first would depend on it. Deferring every
 * member to first use removes the question: each is computed when something asks for it, by
 * which point every object it needs is initialised. The requirement this places on the object is
 * therefore that it hold no strict member.
 *
 * Laziness also matches what the calendars cost. Generating one means evaluating its rules
 * across a hundred and fifty years, so an application that adjusts dates against London alone
 * pays for London alone, and pays once: a `lazy val` is computed at most once however many
 * threads reach it together. That property survives being presented as reference data:
 * `ReferenceData.standard` is built from [[deferredByIdentifier]], which hands the set over as
 * ways of obtaining its calendars, so resolving one identifier against the standard store
 * generates one calendar. Only [[all]], [[minimal]] and the enumeration members of the store
 * itself generate the whole set, and each of them says so.
 *
 * All members are immutable and safe to share between threads.
 *
 * @see [[GlobalHolidayCalendars]] for the rules that produce the generated calendars
 * @see [[HolidayCalendarData]] for the published dates of the Thai bank calendar
 * @see [[HolidayCalendars]] for looking a built-in calendar up by name, and for the four
 *   name-derived calendars under their own names
 */
object StandardHolidayCalendars {

  // The calendars derived from rules. Each is generated on first use, and at most once, and
  // every later use is given the calendar generated then.

  /** The London holiday calendar, `GBLO`, covering 1950 to 2099. */
  lazy val GBLO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateLondon()

  /** The Paris holiday calendar, `FRPA`, covering 1950 to 2099. */
  lazy val FRPA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateParis()

  /** The Frankfurt holiday calendar, `DEFR`, covering 1950 to 2099. */
  lazy val DEFR: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateFrankfurt()

  /** The Zurich holiday calendar, `CHZU`, covering 1950 to 2099. */
  lazy val CHZU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateZurich()

  /**
   * The European TARGET settlement calendar, `EUTA`, covering 1997 to 2099.
   *
   * The range starts later than every other generated calendar because the system this
   * calendar describes began its testing phase in 1997.
   */
  lazy val EUTA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateEuropeanTarget()

  /** The United States government securities calendar, `USGS`, covering 1950 to 2099. */
  lazy val USGS: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateUsGovtSecurities()

  /** The New York holiday calendar, `USNY`, covering 1950 to 2099. */
  lazy val USNY: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateUsNewYork()

  /** The New York Federal Reserve calendar, `NYFD`, covering 1950 to 2099. */
  lazy val NYFD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewYorkFed()

  /** The New York Stock Exchange calendar, `NYSE`, covering 1950 to 2099. */
  lazy val NYSE: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewYorkStockExchange()

  /** The Tokyo holiday calendar, `JPTO`, covering 1950 to 2099. */
  lazy val JPTO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateTokyo()

  /** The Sydney holiday calendar, `AUSY`, covering 1950 to 2099. */
  lazy val AUSY: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateSydney()

  /** The Brazilian bank calendar, `BRBD`, covering 1950 to 2099. */
  lazy val BRBD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateBrazil()

  /** The Montreal holiday calendar, `CAMO`, covering 1950 to 2099. */
  lazy val CAMO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateMontreal()

  /** The Toronto holiday calendar, `CATO`, covering 1950 to 2099. */
  lazy val CATO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateToronto()

  /** The Prague holiday calendar, `CZPR`, covering 1950 to 2099. */
  lazy val CZPR: ImmutableHolidayCalendar = GlobalHolidayCalendars.generatePrague()

  /** The Copenhagen holiday calendar, `DKCO`, covering 1950 to 2099. */
  lazy val DKCO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateCopenhagen()

  /**
   * The Budapest holiday calendar, `HUBU`, covering 1950 to 2099.
   *
   * Alone among these calendars its weekend is Sunday only, because Hungary works some
   * Saturdays to bridge holidays; the Saturdays that are not worked are holidays listed one by
   * one instead of following from a weekend rule.
   */
  lazy val HUBU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateBudapest()

  /** The Mexico City holiday calendar, `MXMC`, covering 1950 to 2099. */
  lazy val MXMC: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateMexicoCity()

  /** The Oslo holiday calendar, `NOOS`, covering 1950 to 2099. */
  lazy val NOOS: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateOslo()

  /** The Auckland holiday calendar, `NZAU`, covering 1950 to 2099. */
  lazy val NZAU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateAuckland()

  /** The Wellington holiday calendar, `NZWE`, covering 1950 to 2099. */
  lazy val NZWE: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateWellington()

  /**
   * The New Zealand bank calendar, `NZBD`, covering 1950 to 2099.
   *
   * The national calendar, observing the holidays common to the whole country rather than the
   * anniversary day of a single province. It is the one built-in calendar with no constant in
   * [[HolidayCalendarIds]], so its identifier is the one its own generator gives it.
   */
  lazy val NZBD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewZealand()

  /** The Warsaw holiday calendar, `PLWA`, covering 1950 to 2099. */
  lazy val PLWA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateWarsaw()

  /** The Stockholm holiday calendar, `SEST`, covering 1950 to 2099. */
  lazy val SEST: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateStockholm()

  /** The Johannesburg holiday calendar, `ZAJO`, covering 1950 to 2099. */
  lazy val ZAJO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateJohannesburg()

  /**
   * The Thai bank calendar, `THBA`, covering the published years 2005 to 2079.
   *
   * The only built-in calendar whose dates are published rather than derived from rules, so it
   * is built from the table [[HolidayCalendarData]] holds rather than from a generator. The
   * dates are taken exactly as published, including the one that falls at a weekend, and the
   * weekend is Saturday and Sunday; no date is declared a business day in spite of them.
   *
   * Outside the published years the calendar applies its weekend alone, which is the behaviour
   * of every calendar here asked about a year it holds no data for.
   */
  lazy val THBA: ImmutableHolidayCalendar =
    ImmutableHolidayCalendar.of(
      HolidayCalendarIds.THBA,
      HolidayCalendarData.thbaHolidays,
      HolidayCalendarData.thbaWeekendDays)

  // The calendars whose whole content follows from their names. These are the same values
  // `HolidayCalendars` publishes; they are named here as well so that this object is the
  // complete built-in set, and so that `all` and `minimal` are assembled from members of it.

  /**
   * The calendar declaring no holidays and no weekend, `NoHolidays`.
   *
   * Every day is a business day, which is how code says that no holiday calendar applies.
   */
  lazy val NO_HOLIDAYS: HolidayCalendar = NoHolidays

  /** The calendar whose only holidays are Saturday and Sunday, `Sat/Sun`. */
  lazy val SAT_SUN: HolidayCalendar = SatSun

  /** The calendar whose only holidays are Friday and Saturday, `Fri/Sat`. */
  lazy val FRI_SAT: HolidayCalendar = FriSat

  /** The calendar whose only holidays are Thursday and Friday, `Thu/Fri`. */
  lazy val THU_FRI: HolidayCalendar = ThuFri

  /**
   * Every holiday calendar built into this library, each keyed by its own identifier.
   *
   * Thirty entries: the twenty-five generated calendars, the published Thai calendar, and the
   * four calendars whose content follows from their names. Every entry is keyed by the
   * identifier its own calendar carries, so `all(id).id == id` holds throughout.
   *
   * These are the calendars `ReferenceData.standard` answers for, and so this is the content
   * that resolves an identifier such as `GBLO` for code that was given no reference data of its
   * own - though the standard store reads [[deferredByIdentifier]] rather than this map, so
   * resolving one identifier against it generates one calendar. It is a total map: there is no
   * entry for an identifier this library does not define, and a caller asking for one gets an
   * empty `Option` from `get` rather than a failure.
   *
   * Typed as a map of identifier to calendar, it is also an iterable of its pairs, which is
   * what lets it be handed to the reference data factories in the root package without a cast
   * or a rebuild: a map is invariant in its key type, but `Iterable` and a pair are both
   * covariant, so a `Map[HolidayCalendarId, HolidayCalendar]` is an
   * `Iterable[(ReferenceDataId[_], Any)]` by ordinary subtyping.
   *
   * Computed on first use, and the member of this object that generates every calendar in it:
   * it exists for code that has to '''enumerate''' the built-in set as values - to report it, to
   * assert over it, or to build a store that is eager by construction - which cannot be done
   * without generating all of it. Code that needs one calendar should name that calendar -
   * `StandardHolidayCalendars.GBLO` - or look it up by name through [[byName]], which generates
   * the calendar it finds and no other, and code that needs the set as reference data should use
   * `ReferenceData.standard`, which generates the calendars it is asked for.
   *
   * @return the built-in calendars by identifier
   */
  lazy val all: Map[HolidayCalendarId, HolidayCalendar] = generatedFrom(builtIn)

  /**
   * Every holiday calendar built into this library as a way of obtaining it, keyed by its own
   * identifier, with none of them generated.
   *
   * The same thirty identifiers [[all]] holds, mapped to the registrations this object is
   * written as rather than to the calendars they produce. Building this view generates nothing,
   * for the reason [[keyedBy]] gives - a key is read from an identifier, never from a calendar -
   * so it is the set presented in a form whose cost is paid one calendar at a time.
   *
   * This is what `ReferenceData.standard` is built from, through
   * `ImmutableReferenceData.ofDeferredMap`: the standard store files each of these ways of
   * obtaining a calendar under its identifier and runs the one a lookup asks for, so a caller
   * that resolves `GBLO` generates London and not the other twenty-nine. The two-type-parameter
   * bound of that factory is satisfied here exactly as `ofMap`'s is by [[all]], `HolidayCalendarId`
   * being a `ReferenceDataId[HolidayCalendar]`.
   *
   * It is visible within `strata-basics` rather than published because it is the shape reference
   * data is assembled from, not one a caller has a use for: code outside this module reads the
   * calendars through `ReferenceData.standard`, through [[all]], or by name through [[byName]].
   *
   * @return the ways of obtaining the built-in calendars, by identifier
   */
  private[basics] lazy val deferredByIdentifier: Map[HolidayCalendarId, () => HolidayCalendar] =
    keyedBy(builtIn)(id => id)

  /**
   * The built-in calendars that carry no market convention of their own, by identifier.
   *
   * Four entries: the no-holidays calendar and the Saturday/Sunday, Friday/Saturday and
   * Thursday/Friday weekend calendars. Their contents follow from their names, so no
   * application has anything to disagree with, which is why these four - and only these four -
   * are the set `ReferenceData.of` places underneath a caller's own entries and the set
   * `ReferenceData.minimal` presents. They are a subset of [[all]].
   *
   * @return the weekend and no-holiday calendars by identifier
   */
  lazy val minimal: Map[HolidayCalendarId, HolidayCalendar] = generatedFrom(nameDerived)

  /**
   * Finds a built-in calendar by its canonical name.
   *
   * The name is matched exactly, as the calendar itself spells it: `GBLO`, `Sat/Sun`,
   * `NoHolidays`. This is the view to use where a name is already known to be canonical - a name
   * this library itself wrote out, for instance, as it does in the JSON form of a calendar.
   *
   * Composite names such as `GBLO+USNY` are not built-in calendars and are not found here;
   * `HolidayCalendars.of` is the entry point that understands them, and it reports an
   * unknown name as a failure rather than as an empty result.
   *
   * Only the calendar found is generated. The view this searches maps each name to a way of
   * obtaining its calendar rather than to the calendar itself, so asking for London costs
   * London: the other twenty-five remain ungenerated, however many times this is called.
   *
   * @param name  the canonical name of the calendar, such as `GBLO`
   * @return the calendar of that name, or empty where this library defines no calendar of it
   */
  def byName(name: String): Option[HolidayCalendar] = generate(byCanonicalName.get(name))

  /**
   * Finds a built-in calendar by name, ignoring the case the name was written in.
   *
   * The name given is upper-cased in the English locale and matched against the upper-cased
   * names of the built-in calendars, so `gblo`, `GBLO` and `Gblo` all find the London
   * calendar, and `sat/sun` finds `Sat/Sun`. The locale is named explicitly, and is English
   * rather than the default of the host, so that the built-in set cannot be found differently
   * on two machines.
   *
   * This is the lenient view. It is what lets a day count written `Bus/252 gblo` name the same
   * day count as `Bus/252 GBLO`. Where a name is known to be canonical, prefer [[byName]]: it
   * answers without folding case and so cannot accept a name this library would not have
   * written.
   *
   * As with [[byName]], only the calendar found is generated.
   *
   * @param name  the name of the calendar in any case, such as `gblo`
   * @return the calendar of that name, or empty where this library defines no calendar of it
   */
  def byUpperName(name: String): Option[HolidayCalendar] =
    generate(byUpperCaseName.get(name.toUpperCase(Locale.ENGLISH)))

  /**
   * Finds a built-in calendar by either of the two names it answers to.
   *
   * Those names are two per calendar: the canonical name the calendar carries, and the English
   * upper-case of that name - so `GBLO`, `Sat/Sun`, `SAT/SUN` and `NOHOLIDAYS` are all names of
   * built-in calendars. The canonical name is tried first, and the match is exact within the two
   * key spaces: this does not fold the case of the name it is given, so a name in any other case
   * - `Gblo`, `sat/sun` - is not found here, which is the difference from [[byUpperName]].
   *
   * This is what `HolidayCalendars.of` resolves a simple name with, and that method reports a
   * name outside the built-in set as a failure. Only the calendar found is generated.
   *
   * @param name  the name of the calendar, canonical or upper-case
   * @return the calendar of that name, or empty where this library defines no calendar of it
   */
  private[date] def byRegisteredName(name: String): Option[HolidayCalendar] =
    generate(byCanonicalName.get(name).orElse(byUpperCaseName.get(name)))

  /**
   * Checks whether a calendar '''is''' one of the calendars built into this library.
   *
   * The test is reference identity against the built-in calendar of the same name, not equality
   * with it. That distinction is the whole point of this method: a calendar carrying holiday
   * data is equal to any calendar of the same identifier, whatever dates it holds, so equality
   * cannot tell the library's own `GBLO` from an application's `GBLO` - and the JSON form of a
   * calendar, which writes a built-in calendar as its bare name and everything else as its
   * dates, has to be able to.
   *
   * Only the built-in calendar of the name given is generated, so this costs at most one
   * calendar rather than the whole set.
   *
   * @param calendar  the calendar to test
   * @return true where the calendar is this library's own instance of its name
   */
  private[date] def isBuiltIn(calendar: HolidayCalendar): Boolean =
    byCanonicalName.get(calendar.name).exists(builtInCalendar => builtInCalendar() eq calendar)

  /**
   * A built-in calendar, as its identifier and a way of obtaining it.
   *
   * The pair - rather than the calendar itself - is what the registrations below are made of,
   * and it is what keeps the laziness of this object meaningful. A map of identifier to calendar
   * cannot be built without building every calendar in it, so any view keyed by name would
   * generate all twenty-six dated calendars the first time one name was looked up; a map of
   * identifier to `() => calendar` is built without generating any of them, and reading one
   * entry generates one calendar. The identifier is available without the calendar because
   * every built-in calendar is identified by a constant of [[HolidayCalendarIds]], or, for the
   * one calendar that has no constant there, by its own name.
   */
  private type Registration = (HolidayCalendarId, () => HolidayCalendar)

  /**
   * The calendars whose whole content follows from their names.
   *
   * Held as a list so that [[minimal]] and [[builtIn]] are both assembled from it and cannot
   * fall out of step: these four are exactly the calendars that belong in the minimal set, and
   * they are also the first entries of the complete one.
   */
  private lazy val nameDerived: List[Registration] =
    List(
      HolidayCalendarIds.NO_HOLIDAYS -> (() => NO_HOLIDAYS),
      HolidayCalendarIds.SAT_SUN -> (() => SAT_SUN),
      HolidayCalendarIds.FRI_SAT -> (() => FRI_SAT),
      HolidayCalendarIds.THU_FRI -> (() => THU_FRI))

  /**
   * Every built-in calendar, in claim order: the four name-derived calendars, then the published
   * calendar, then the generated ones.
   *
   * The order is part of the contract of the two name views, which resolve a name to the calendar
   * that claims it first. No two calendars in this list claim the same name, so no calendar here
   * displaces another; holding the order means that a calendar added to the list takes effect at
   * the position it is written rather than displacing one already there.
   */
  private lazy val builtIn: List[Registration] =
    nameDerived ::: (HolidayCalendarIds.THBA -> (() => THBA)) :: generated

  /**
   * The calendars derived from rules, in the order their identifiers sort.
   *
   * The identifier of each is its constant in [[HolidayCalendarIds]], except for the New Zealand
   * bank calendar, which has no constant there and so names itself. Each identifier written here
   * is the one its own calendar carries, which is what makes writing them down beside the
   * calendars safe: the point of doing so is that a name can be looked up without generating
   * anything.
   */
  private lazy val generated: List[Registration] =
    List(
      HolidayCalendarIds.AUSY -> (() => AUSY),
      HolidayCalendarIds.BRBD -> (() => BRBD),
      HolidayCalendarIds.CAMO -> (() => CAMO),
      HolidayCalendarIds.CATO -> (() => CATO),
      HolidayCalendarIds.CHZU -> (() => CHZU),
      HolidayCalendarIds.CZPR -> (() => CZPR),
      HolidayCalendarIds.DEFR -> (() => DEFR),
      HolidayCalendarIds.DKCO -> (() => DKCO),
      HolidayCalendarIds.EUTA -> (() => EUTA),
      HolidayCalendarIds.FRPA -> (() => FRPA),
      HolidayCalendarIds.GBLO -> (() => GBLO),
      HolidayCalendarIds.HUBU -> (() => HUBU),
      HolidayCalendarIds.JPTO -> (() => JPTO),
      HolidayCalendarIds.MXMC -> (() => MXMC),
      HolidayCalendarIds.NOOS -> (() => NOOS),
      HolidayCalendarIds.NYFD -> (() => NYFD),
      HolidayCalendarIds.NYSE -> (() => NYSE),
      HolidayCalendarIds.NZAU -> (() => NZAU),
      HolidayCalendarId.of("NZBD") -> (() => NZBD),
      HolidayCalendarIds.NZWE -> (() => NZWE),
      HolidayCalendarIds.PLWA -> (() => PLWA),
      HolidayCalendarIds.SEST -> (() => SEST),
      HolidayCalendarIds.USGS -> (() => USGS),
      HolidayCalendarIds.USNY -> (() => USNY),
      HolidayCalendarIds.ZAJO -> (() => ZAJO))

  /** The built-in calendars keyed by the name each of them carries, none of them generated. */
  private lazy val byCanonicalName: Map[String, () => HolidayCalendar] =
    keyedBy(builtIn)(id => id.name)

  /**
   * The built-in calendars keyed by the English upper-case of the name each of them carries,
   * none of them generated.
   */
  private lazy val byUpperCaseName: Map[String, () => HolidayCalendar] =
    keyedBy(builtIn)(id => id.name.toUpperCase(Locale.ENGLISH))

  /**
   * Keys the registrations of built-in calendars, letting the first claim of a key win.
   *
   * Building the views this way rather than with a straight conversion to a map is what makes the
   * first claim of a key win: a key is taken only where it is free, so the earlier entry of the
   * list decides what a name means, where a straight conversion would silently give the key to
   * the last claim instead.
   *
   * The key is taken from the identifier of a registration, never from its calendar, so that
   * building a view generates nothing.
   *
   * @param source  the registrations, in the order they are registered
   * @param keyOf  the key of an identifier
   * @tparam K  the type of the key
   * @return the registrations by key, each key held by the first calendar that claimed it
   */
  private def keyedBy[K](source: List[Registration])(
      keyOf: HolidayCalendarId => K): Map[K, () => HolidayCalendar] =

    source.foldLeft(Map.empty[K, () => HolidayCalendar]) {
      case (keyed, (id, calendar)) =>
        val key = keyOf(id)
        if (keyed.contains(key)) keyed else keyed.updated(key, calendar)
    }

  /**
   * Generates the calendars of a list of registrations, keyed by identifier.
   *
   * This is the deliberate full-materialisation path, used by [[all]] and [[minimal]] alone:
   * every calendar of the list is generated. Nothing else in this object forces more than the
   * one calendar it was asked for.
   *
   * @param source  the registrations, in the order they are registered
   * @return the calendars by identifier
   */
  private def generatedFrom(source: List[Registration]): Map[HolidayCalendarId, HolidayCalendar] =
    keyedBy(source)(id => id).map { case (id, calendar) => id -> calendar() }

  /**
   * Generates the calendar a view answered with, where it answered with one.
   *
   * @param found  the way of obtaining the calendar, where a view held one
   * @return the calendar, or empty where the view held none
   */
  private def generate(found: Option[() => HolidayCalendar]): Option[HolidayCalendar] =
    found.map(calendar => calendar())
}
