/*
 * Copyright (C) 2015 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.basics.date

import java.util.Locale

import scala.collection.immutable.List
import scala.collection.immutable.Map

/**
 * The holiday calendars built into this library, as values, keyed by their identifiers.
 *
 * A holiday calendar is reference data: code that adjusts a date asks for a calendar by
 * identifier and is given one by the [[com.opengamma.strata.basics.ReferenceData]] it was
 * passed, so that an application whose own holidays are what matter can supply them. Most
 * applications, and every test and demonstration, want the calendars this library already
 * knows about instead, and this object is where those live. It is the single place the
 * built-in set is written down, and `ReferenceData.standard` is exactly this set presented as
 * reference data.
 *
 * Thirty calendars are published, in three groups and from three different kinds of source:
 *
 *   - twenty-five national and exchange calendars derived from rules, produced by
 *     [[GlobalHolidayCalendars]] - `GBLO` through `CZPR` below;
 *   - one calendar whose dates are published rather than derived, the Thai bank calendar
 *     [[THBA]], built from the table in [[HolidayCalendarData]];
 *   - four calendars whose whole content follows from their names: [[NO_HOLIDAYS]],
 *     [[SAT_SUN]], [[FRI_SAT]] and [[THU_FRI]].
 *
 * ===What this replaces===
 *
 * The library being ported assembled the same thirty calendars at run time, from three
 * providers named in a configuration resource on the classpath and consulted in order, with
 * the first registration of a name winning: the four weekend and no-holiday constants, then a
 * loader that parsed published calendar data, then a loader that read the rule-generated
 * calendars back from a binary cache. Each provider registered every calendar twice, under its
 * name and under the English upper-case of its name, and the registry then offered the set
 * re-keyed by canonical name alone.
 *
 * All of that is now data. The providers, the registry, the cache and the parsing are gone; the
 * behaviour that depended on them is not. The set and its order are reproduced here - the four
 * name-derived calendars, then the published calendar, then the generated ones, first name
 * winning - and the two name views the registry offered are reproduced by [[byName]] and
 * [[byUpperName]]. Nothing here reads the classpath, the file system or any other source
 * outside this build, so the built-in set cannot differ between two runs or two deployments of
 * the same version.
 *
 * ===Initialisation order (read before editing)===
 *
 * Every member of this object is a `lazy val`, and that is load-bearing rather than merely an
 * optimisation. This object sits in a cycle the design intends: the JSON form of a calendar in
 * [[HolidayCalendar]] names the built-in calendars and so reads this object, the calendars are
 * generated by [[GlobalHolidayCalendars]], and those generators build their results with
 * `ImmutableHolidayCalendar.of` - back in [[HolidayCalendar]]. `ReferenceData.standard`, itself
 * computed on first use, reads [[all]]. A strict `val` anywhere in that cycle would make the
 * order in which these objects happen to be initialised load-bearing, and the value observed by
 * whichever member of the cycle ran first would depend on it. Deferring every member to first
 * use removes the question: each is computed when something asks for it, by which point every
 * object it needs is initialised. Anything added here must keep that property.
 *
 * Laziness also matches what the calendars cost. Generating one means evaluating its rules
 * across a hundred and fifty years, so an application that adjusts dates against London alone
 * pays for London alone, and pays once: a `lazy val` is computed at most once however many
 * threads reach it together.
 *
 * All members are immutable and safe to share between threads.
 *
 * @see [[GlobalHolidayCalendars]] for the rules that produce the generated calendars
 * @see [[HolidayCalendarData]] for the published dates of the Thai bank calendar
 * @see [[HolidayCalendars]] for looking a built-in calendar up by name, and for the four
 *   name-derived calendars under their own names
 */
object StandardHolidayCalendars {

  //-------------------------------------------------------------------------
  // The calendars derived from rules. Each is generated on first use, and at most once.

  /** The London holiday calendar, `GBLO`, covering 1950 to 2099. */
  lazy val GBLO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateLondon()

  /** The Paris holiday calendar, `FRPA`, covering 1950 to 2099. */
  lazy val FRPA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateParis()

  /** The Frankfurt holiday calendar, `DEFR`, covering 1950 to 2099. */
  lazy val DEFR: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateFrankfurt()

  /** The Zurich holiday calendar, `CHZU`, covering 1950 to 2099. */
  lazy val CHZU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateZurich()

  /**
   * The European TARGET settlement calendar, `EUTA`, covering 1997 to 2099.
   *
   * The range starts later than every other generated calendar because the system this
   * calendar describes began its testing phase in 1997.
   */
  lazy val EUTA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateEuropeanTarget()

  /** The United States government securities calendar, `USGS`, covering 1950 to 2099. */
  lazy val USGS: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateUsGovtSecurities()

  /** The New York holiday calendar, `USNY`, covering 1950 to 2099. */
  lazy val USNY: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateUsNewYork()

  /** The New York Federal Reserve calendar, `NYFD`, covering 1950 to 2099. */
  lazy val NYFD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewYorkFed()

  /** The New York Stock Exchange calendar, `NYSE`, covering 1950 to 2099. */
  lazy val NYSE: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewYorkStockExchange()

  /** The Tokyo holiday calendar, `JPTO`, covering 1950 to 2099. */
  lazy val JPTO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateTokyo()

  /** The Sydney holiday calendar, `AUSY`, covering 1950 to 2099. */
  lazy val AUSY: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateSydney()

  /** The Brazilian bank calendar, `BRBD`, covering 1950 to 2099. */
  lazy val BRBD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateBrazil()

  /** The Montreal holiday calendar, `CAMO`, covering 1950 to 2099. */
  lazy val CAMO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateMontreal()

  /** The Toronto holiday calendar, `CATO`, covering 1950 to 2099. */
  lazy val CATO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateToronto()

  /** The Prague holiday calendar, `CZPR`, covering 1950 to 2099. */
  lazy val CZPR: ImmutableHolidayCalendar = GlobalHolidayCalendars.generatePrague()

  /** The Copenhagen holiday calendar, `DKCO`, covering 1950 to 2099. */
  lazy val DKCO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateCopenhagen()

  /**
   * The Budapest holiday calendar, `HUBU`, covering 1950 to 2099.
   *
   * Alone among these calendars its weekend is Sunday only, because Hungary works some
   * Saturdays to bridge holidays; the Saturdays that are not worked are holidays listed one by
   * one instead of following from a weekend rule.
   */
  lazy val HUBU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateBudapest()

  /** The Mexico City holiday calendar, `MXMC`, covering 1950 to 2099. */
  lazy val MXMC: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateMexicoCity()

  /** The Oslo holiday calendar, `NOOS`, covering 1950 to 2099. */
  lazy val NOOS: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateOslo()

  /** The Auckland holiday calendar, `NZAU`, covering 1950 to 2099. */
  lazy val NZAU: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateAuckland()

  /** The Wellington holiday calendar, `NZWE`, covering 1950 to 2099. */
  lazy val NZWE: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateWellington()

  /**
   * The New Zealand bank calendar, `NZBD`, covering 1950 to 2099.
   *
   * The national calendar, observing the holidays common to the whole country rather than the
   * anniversary day of a single province. It is the one built-in calendar with no constant in
   * [[HolidayCalendarIds]], exactly as in the library being ported, so its identifier is the
   * one its own generator gives it.
   */
  lazy val NZBD: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateNewZealand()

  /** The Warsaw holiday calendar, `PLWA`, covering 1950 to 2099. */
  lazy val PLWA: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateWarsaw()

  /** The Stockholm holiday calendar, `SEST`, covering 1950 to 2099. */
  lazy val SEST: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateStockholm()

  /** The Johannesburg holiday calendar, `ZAJO`, covering 1950 to 2099. */
  lazy val ZAJO: ImmutableHolidayCalendar = GlobalHolidayCalendars.generateJohannesburg()

  //-------------------------------------------------------------------------
  /**
   * The Thai bank calendar, `THBA`, covering the published years 2005 to 2079.
   *
   * The only built-in calendar whose dates are published rather than derived from rules, so it
   * is built from the table [[HolidayCalendarData]] holds rather than from a generator. The
   * dates are taken exactly as published, including the one that falls at a weekend, and the
   * weekend is Saturday and Sunday; no date is declared a business day in spite of them.
   *
   * Outside the published years the calendar applies its weekend alone, which is the behaviour
   * of every calendar here asked about a year it holds no data for.
   */
  lazy val THBA: ImmutableHolidayCalendar =
    ImmutableHolidayCalendar.of(
      HolidayCalendarIds.THBA,
      HolidayCalendarData.thbaHolidays,
      HolidayCalendarData.thbaWeekendDays)

  //-------------------------------------------------------------------------
  // The calendars whose whole content follows from their names. These are the same values
  // `HolidayCalendars` publishes; they are named here as well so that this object is the
  // complete built-in set, and so that `all` and `minimal` are assembled from members of it.

  /**
   * The calendar declaring no holidays and no weekend, `NoHolidays`.
   *
   * Every day is a business day, which is how code says that no holiday calendar applies.
   */
  lazy val NO_HOLIDAYS: HolidayCalendar = NoHolidays

  /** The calendar whose only holidays are Saturday and Sunday, `Sat/Sun`. */
  lazy val SAT_SUN: HolidayCalendar = SatSun

  /** The calendar whose only holidays are Friday and Saturday, `Fri/Sat`. */
  lazy val FRI_SAT: HolidayCalendar = FriSat

  /** The calendar whose only holidays are Thursday and Friday, `Thu/Fri`. */
  lazy val THU_FRI: HolidayCalendar = ThuFri

  //-------------------------------------------------------------------------
  /**
   * Every holiday calendar built into this library, each keyed by its own identifier.
   *
   * Thirty entries: the twenty-five generated calendars, the published Thai calendar, and the
   * four calendars whose content follows from their names. Every entry is keyed by the
   * identifier its own calendar carries, so `all(id).id == id` holds throughout - the invariant
   * the registry of the library being ported established by re-keying its providers' output by
   * canonical name before publishing it.
   *
   * This is the set `ReferenceData.standard` presents, and so it is what resolves an identifier
   * such as `GBLO` for code that was given no reference data of its own. It is a total map:
   * there is no entry for an identifier this library does not define, and a caller asking for
   * one gets an empty `Option` from `get` rather than a failure.
   *
   * Typed as a map of identifier to calendar, it is also an iterable of its pairs, which is
   * what lets it be handed to the reference data factories in the root package without a cast
   * or a rebuild: a map is invariant in its key type, but `Iterable` and a pair are both
   * covariant, so a `Map[HolidayCalendarId, HolidayCalendar]` is an
   * `Iterable[(ReferenceDataId[_], Any)]` by ordinary subtyping.
   *
   * Computed on first use, which generates every calendar in it. Code that needs one calendar
   * should name that calendar - `StandardHolidayCalendars.GBLO` - rather than index this map.
   *
   * @return the built-in calendars by identifier
   */
  lazy val all: Map[HolidayCalendarId, HolidayCalendar] = keyedBy(builtIn)(_.id)

  /**
   * The built-in calendars that carry no market convention of their own, by identifier.
   *
   * Four entries: the no-holidays calendar and the Saturday/Sunday, Friday/Saturday and
   * Thursday/Friday weekend calendars. Their contents follow from their names, so no
   * application has anything to disagree with, which is why these four - and only these four -
   * are the set `ReferenceData.of` places underneath a caller's own entries and the set
   * `ReferenceData.minimal` presents. They are a subset of [[all]].
   *
   * @return the weekend and no-holiday calendars by identifier
   */
  lazy val minimal: Map[HolidayCalendarId, HolidayCalendar] = keyedBy(nameDerived)(_.id)

  //-------------------------------------------------------------------------
  /**
   * Finds a built-in calendar by its canonical name.
   *
   * The name is matched exactly, as the calendar itself spells it: `GBLO`, `Sat/Sun`,
   * `NoHolidays`. This is the view the registry of the library being ported published as its
   * normalised set, and the one to use where a name is already known to be canonical - a name
   * this library itself wrote out, for instance, as it does in the JSON form of a calendar.
   *
   * Composite names such as `GBLO+USNY` are not built-in calendars and are not found here;
   * `HolidayCalendars.of` is the entry point that understands them, and it reports an
   * unknown name as a failure rather than as an empty result.
   *
   * @param name  the canonical name of the calendar, such as `GBLO`
   * @return the calendar of that name, or empty where this library defines no calendar of it
   */
  def byName(name: String): Option[HolidayCalendar] = byCanonicalName.get(name)

  /**
   * Finds a built-in calendar by name, ignoring the case the name was written in.
   *
   * The name given is upper-cased in the English locale and matched against the upper-cased
   * names of the built-in calendars, so `gblo`, `GBLO` and `Gblo` all find the London
   * calendar, and `sat/sun` finds `Sat/Sun`. The locale is named explicitly, and is English
   * rather than the default of the host, so that the built-in set cannot be found differently
   * on two machines - the same choice, for the same reason, as the library being ported made
   * when it registered each calendar under the English upper-case of its name alongside its
   * canonical one.
   *
   * This is the lenient view. It is what lets a day count written `Bus/252 gblo` name the same
   * day count as `Bus/252 GBLO`, matching the case-insensitive treatment of such a name in the
   * library being ported. Where a name is known to be canonical, prefer [[byName]]: it answers
   * without folding case and so cannot accept a name this library would not have written.
   *
   * @param name  the name of the calendar in any case, such as `gblo`
   * @return the calendar of that name, or empty where this library defines no calendar of it
   */
  def byUpperName(name: String): Option[HolidayCalendar] =
    byUpperCaseName.get(name.toUpperCase(Locale.ENGLISH))

  //-------------------------------------------------------------------------
  /**
   * The calendars whose whole content follows from their names.
   *
   * Held as a list so that [[minimal]] and [[builtIn]] are both assembled from it and cannot
   * fall out of step: these four are exactly the calendars that belong in the minimal set, and
   * they are also the first entries of the complete one.
   */
  private lazy val nameDerived: List[HolidayCalendar] =
    List(NO_HOLIDAYS, SAT_SUN, FRI_SAT, THU_FRI)

  /**
   * Every built-in calendar, in the order the calendars of the library being ported were
   * registered: the four name-derived calendars, then the published calendar, then the
   * generated ones.
   *
   * The order is kept because the registry it reproduces resolved a name to the calendar that
   * claimed it first. No two calendars here claim the same name, so the order changes nothing
   * today; keeping it means that a calendar added in the future takes effect exactly where the
   * original would have put it, rather than silently displacing one that was already there.
   */
  private lazy val builtIn: List[HolidayCalendar] =
    nameDerived ::: THBA :: generated

  /** The calendars derived from rules, in the order their identifiers sort. */
  private lazy val generated: List[HolidayCalendar] =
    List(
      AUSY,
      BRBD,
      CAMO,
      CATO,
      CHZU,
      CZPR,
      DEFR,
      DKCO,
      EUTA,
      FRPA,
      GBLO,
      HUBU,
      JPTO,
      MXMC,
      NOOS,
      NYFD,
      NYSE,
      NZAU,
      NZBD,
      NZWE,
      PLWA,
      SEST,
      USGS,
      USNY,
      ZAJO)

  /** The built-in calendars keyed by the name each of them carries. */
  private lazy val byCanonicalName: Map[String, HolidayCalendar] = keyedBy(builtIn)(_.id.name)

  /** The built-in calendars keyed by the English upper-case of the name each of them carries. */
  private lazy val byUpperCaseName: Map[String, HolidayCalendar] =
    keyedBy(builtIn)(calendar => calendar.id.name.toUpperCase(Locale.ENGLISH))

  /**
   * Keys a list of calendars, letting the first claim of a key win.
   *
   * Building the views this way rather than with a straight conversion to a map states the rule
   * the registry being replaced followed: it registered each calendar only where the key was
   * free, so the provider consulted first decided what a name meant. A straight conversion
   * would silently give the key to the last claim instead.
   *
   * @param source  the calendars, in the order they are registered
   * @param keyOf  the key of a calendar
   * @tparam K  the type of the key
   * @return the calendars by key, each key held by the first calendar that claimed it
   */
  private def keyedBy[K](source: List[HolidayCalendar])(
      keyOf: HolidayCalendar => K): Map[K, HolidayCalendar] =

    source.foldLeft(Map.empty[K, HolidayCalendar]) { (keyed, calendar) =>
      val key = keyOf(calendar)
      if (keyed.contains(key)) keyed else keyed.updated(key, calendar)
    }
}
